### ISSUE TITLE
win11 测试无法使用，图片无法拖动到软件里，也无法通过软件里点击添加图片

### ISSUE THREAD

**Issue by cced3000** [receyuki/stable-diffusion-prompt-reader#1]
如题，是BUG、还是兼容问题？

**Comment by receyuki** [comment]
> 如题，是BUG、还是兼容问题？

试一下我刚传的1.0.1.我加了个提示
如果显示No data detected or unsupported formats说明检测不到prompt
如果你确定文件是由webui生成的原文件可以打包传一份我看下情况
或者如果你的文件是由别的工具生成的也可以传一份我看看能不能支持一下
