### ISSUE TITLE
couldn't install it

### ISSUE THREAD

**Issue by WalidAliAlfaid** [receyuki/stable-diffusion-prompt-reader#11]
can you make a colab version

**Comment by receyuki** [comment]
> can you make a colab version

This tool is designed to run offline on your local Mac or PC. You can simply [download excutable](https://github.com/receyuki/stable-diffusion-prompt-reader/releases/latest) and double click to run it. If you have access to the Stable Diffusion webui, you can use the pnginfo feature directly on the webui.
