### ISSUE TITLE
[BUG] Can't open the program

### ISSUE THREAD

**Issue by ViperSniper89** [receyuki/stable-diffusion-prompt-reader#13]
Hi, I'm having an issue when I'm trying to open the program. Is there a way to solve it?

> Traceback (most recent call last):
> File "requests\compat.py", line 11, in <module>
> ModuleNotFoundError: No module named 'chardet'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 1, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "app.py", line 21, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "update_checker.py", line 9, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "requests\__init__.py", line 45, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "requests\exceptions.py", line 9, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "requests\compat.py", line 13, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "charset_normalizer\__init__.py", line 24, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "charset_normalizer\api.py", line 5, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "charset_normalizer\cd.py", line 9, in <module>
> ModuleNotFoundError: No module named 'charset_normalizer.md__mypyc'
>

**Comment by receyuki** [comment]
My bad, I forgot to put the chardet in the requirement.txt. Simply `pip install chardet` will fix it. But the executables I made shouldn't have this problem, so please use the executable in preference.

**Comment by ViperSniper89** [comment]
I already did install the charset-normalizer yet I still get the same error. Tried to uninstall, clear the cache and install again the charset-normalizer nothing works.

**Comment by receyuki** [comment]
Which version of the app are you currently using? windows? mac? Or running on your onw python?

**Comment by ViperSniper89** [comment]
I have the latest version of python 3.11..3 and Chardet 5.1.0 running on Windows 11 22H2

**Comment by receyuki** [comment]
[SD-Prompt-Reader-1.3.0.2-#13build1.zip](https://github.com/receyuki/stable-diffusion-prompt-reader/files/11592323/SD-Prompt-Reader-1.3.0.2-.13build1.zip)

I'm still not sure what the problem is. Try this one. If it works, use it instead.

**Comment by ViperSniper89** [comment]
NOt working, I'm still having the same error.

**Comment by receyuki** [comment]
Do you use any antivirus other than Windows Defender?

**Comment by ViperSniper89** [comment]
yes ESET!

**Comment by hugepower** [comment]
See last comment:

https://stackoverflow.com/questions/74182807/no-module-named-charset-normalizer-md-mypyc

**Comment by ViperSniper89** [comment]
Yes, it actually blocked by the antivirus. I whitelisted it and it already works fine.

**Comment by receyuki** [comment]
Then as I mentioned in the [FAQ](https://github.com/receyuki/stable-diffusion-prompt-reader#malware-alert), you can either trust Windows Defender and keep it in the whitelist or use the instruction for Linux users to use this app.
