### ISSUE TITLE
Does Only Work with Images I Generated in the Web UI

### ISSUE THREAD

**Issue by LittleTykha** [receyuki/stable-diffusion-prompt-reader#15]
Hello,

Whenever I drag an image that is not from my Stable Diffusion Outputs folder, it says: ''No data detected or unsupported format''.
Even if it's an image generated from my computer, once transferred from one computer to another, it doesn't work either.

![Capture](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/134748810/455b7611-59fc-4d93-b35d-4672d94b3236)

![Screenshot 2023-05-30 103757](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/134748810/92cbb11d-f92f-43be-bc40-be4f1776f320)

Do you have any clues on why this is happenning?
Thank you!

(edit. corrected my spelling)

**Comment by receyuki** [comment]
It looks like the second image has a very low resolution. This means the second image may have been compressed. So I think that's why it's missing metadata.

**Comment by LittleTykha** [comment]
Oh, I see.
So how can I prevent this issue?

**Comment by receyuki** [comment]
Just don't compress it. As far as I know, any compression will destroy the metadata. Or you can choose to EXPORT the metadata of the original image as a txt file and then import it into the compressed image using EDIT.
