### ISSUE TITLE
MI pro 打开失败

### ISSUE THREAD

**Issue by yh4922** [receyuki/stable-diffusion-prompt-reader#2]
“SD Prompt Reader”已损坏，无法打开。 你应该将它移到废纸篓。

**Comment by receyuki** [comment]
> “SD Prompt Reader”已损坏，无法打开。 你应该将它移到废纸篓。

M1兼容有测过应该是没问题的.八成是没开“允许任何来源下载的app”
给你找了个教程
[https://www.macdo.cn/925.html](https://www.macdo.cn/925.html)
当然原因也很简单..因为没给苹果交一年99刀的保护费..😓
