### ISSUE TITLE
Not working on os.x

### ISSUE THREAD

**Issue by Carloscz16** [receyuki/stable-diffusion-prompt-reader#22]
Hi there
Tried 3 versions,none of them opens on the latest osx.
Greets

**Comment by receyuki** [comment]
Have you tried this?
https://github.com/receyuki/stable-diffusion-prompt-reader#sd-prompt-readerapp-is-damaged-and-cant-be-opend-you-should-move-it-to-the-trash

**Comment by Carloscz16** [comment]
Thank you.
