### ISSUE TITLE
Doesn't work for ComfyUI SDXL flows

### ISSUE THREAD

**Issue by kelzan** [receyuki/stable-diffusion-prompt-reader#25]
Has worked great up until now for ComfyUI generated images, however there's something about the new SDXL flows where it won't read the metadata. I've tried several flows, both version 0.9 and 1.0, but haven't gotten anything to work.
I attached an example image generated by ComfyUI with SDXL1.0.
Love this tool, by the way!
![SDXL_1 0_Output_00001_](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/6321280/3b8eae8a-bb1a-4367-8f2d-ea3cfaab7486)

**Comment by receyuki** [comment]
@kelzan @GlebIgorevich @Marscog @Tikishark777 @lilixil 
Which solution do you guys prefer?  
❤️ for option 1 and 🚀 for option 2
1. Always display Clip G, Clip L and Refiner prompt in separate textboxes.
<img width="1392" alt="截屏2023-08-20 下午9 08 58" src="https://github.com/receyuki/stable-diffusion-prompt-reader/assets/28808141/dc6f9eb1-692f-4d5a-a04e-a72fff46924e">
2. Use tabs to switch between different prompts.
<img width="1392" alt="截屏2023-08-20 下午10 10 25" src="https://github.com/receyuki/stable-diffusion-prompt-reader/assets/28808141/68de0e3c-dfa6-420b-9ca7-2651ed4e4f99">
For me, the second solution looks better, but I'm not sure if it's necessary to keep Clip G, Clip L and Refiner prompt displayed all the time.

**Comment by Marscog** [comment]
❤ I like option 1. I like to see all the info at once.
-thanks

**Comment by Tikishark777** [comment]
I like the second option as well. It's less cluttered and since I mostly only use clip g it fits my purpose. However, I'd be happy with either version. Ty for your time on this project.

**Comment by kelzan** [comment]
If the prompts are short, the first option is nice, however I think I'd prefer the second option the majority of the time.

**Comment by receyuki** [comment]
> I think we need both types and the button for switching between them. 1st is good for the short prompts, but is not good for the long prompts. 2nd is opposite: good for long prompts only.
> 
> But it will be broken again if the workflow has more than 3+3 nodes for prompt. And no ideas how to showing that correctly. Merging all of them is not good idea.


Although I know that theoretically ComfyUI can have more than 2 Ksamplers, I don't understand in what situations users would need more than 3+3 prompts. Do you have any examples for that?

**Comment by receyuki** [comment]
I finally decided to keep both and switch between them using a button.
<img width="1392" alt="截屏2023-08-23 上午12 50 39" src="https://github.com/receyuki/stable-diffusion-prompt-reader/assets/28808141/19bd355d-d396-4621-a753-9f719e827359">

**Comment by Tikishark777** [comment]
Looks great. Good choice.

**Comment by receyuki** [comment]
I just released a new beta version🚀.
Please test it with different sdxl images. If there are any issues, please let me know.

https://github.com/receyuki/stable-diffusion-prompt-reader/releases/tag/v1.3.3-beta.1

**Comment by Tikishark777** [comment]
Unfortunately, it won't work with any of my images.  I do see text for the last box, but the everything is blank.  

<img width="619" alt="image" src="https://github.com/receyuki/stable-diffusion-prompt-reader/assets/136287741/aa1a3ad9-2a8c-4d24-abbd-29c0981ccb5f">

**Comment by receyuki** [comment]
@GlebIgorevich 
```json
    "77": {
        "inputs": {
            "filename_prefix": "ComfyUI_upscaled"
        },
        "class_type": "SaveImage"
    }
```
This workflow looks so weird. Although this node looks fine in ComfyUI, it's not connected to any other nodes in the raw workflow data. It appears to be a bug in ComfyUI or UltimateSDUpscale. But anyway, I've added new logic to handle this situation. Thank you for your help!

**Comment by receyuki** [comment]
[SD-Prompt-Reader-1.3.3-beta.1+dev.1-Windows-x64.zip](https://github.com/receyuki/stable-diffusion-prompt-reader/files/12430883/SD-Prompt-Reader-1.3.3-beta.1%2Bdev.1-Windows-x64.zip)

@GlebIgorevich 
Try this version, images similar to the one above should all work fine now. If there are other images that are not working, please let me know.

@Tikishark777
Try this version first. If it still doesn't work properly, please upload the original image here or send it to my email at [receyuki@gmail.com](mailto:receyuki@gmail.com).

**Comment by Tikishark777** [comment]
Thank you for looking at this further.  I tried the updated version, but still with no luck.  I'm attaching an image from my workflow.  It could be one of my extensions that's throwing everything off.
![gen_00085_](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/136287741/aa8ac52d-253c-407a-8045-703a618600d8)

**Comment by receyuki** [comment]
@Tikishark777 
Oh my goodness, this workflow is truly impressive. I've never seen such a complex workflow before, and almost every node is a custom node.

However, this also means that I'll need a large amount of time to support these custom nodes. Especially with Searge, this extension has significantly different characteristics compared to the original ComfyUI. 

Thus, I'm sorry to say that I might not be able to provide support for Searge. Nevertheless, you can still use the copy button next to the export button to extract all the raw metadata. Although you may not be able to directly discern any useful infomation from it.

**Comment by receyuki** [comment]
@GlebIgorevich I will be releasing beta2 within the next few days to fix the norwegian forest cat. But what I don't understand is that the mermaid image works fine on my end. I guess you might be using the wrong version. But don't worry, give beta2 a try when it's released, and we'll see how it goes.

**Comment by Tikishark777** [comment]
I completely understand.  I do appreciate all you hard work though.  I'm currently trying to replicate some of what Searge is doing without all the custom nodes.  Hopefully, that will help as well.

**Comment by receyuki** [comment]
@Tikishark777 In theory, as long as the workflow uses native KSampler nodes, including "KSampler", "KSamplerAdvanced" and native CLIPTextEncode nodes such as "CLIPTextEncode", "CLIPTextEncodeSDXL" and "CLIPTextEncodeSDXLRefiner" the workflow should be recognised correctly. But, I am aware that this requirement is quite demanding.

**Comment by receyuki** [comment]
@GlebIgorevich 
https://github.com/receyuki/stable-diffusion-prompt-reader/releases/tag/v1.3.3-beta.2
I just released beta 2. Try it out.

**Comment by receyuki** [comment]
@GlebIgorevich This new bug is again caused by new custom nodes, and I will fix it in the next release. 

However, to be honest, the more custom nodes users use, the higher the likelihood that image data won't be read correctly. Civitai's online tools tend to ignore custom nodes, while the diffusion toolkit only directly reads data from KSampler, so it's also unable to handle custom nodes. Perhaps I should consider giving up support for custom nodes.

**Comment by Marscog** [comment]
None of my comfy files work. I think it is because I use SDXL Promp Styler for everything. Here is an example file.
I think it would be difficult to get it to work with comfy since there are infinite workflows.
![ComfyUI CNtest_00039_](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/142053317/b7db457c-e567-49be-b206-7421c3f3b68f)

**Comment by Marscog** [comment]
I'm using a new program now, Fooocus the Moonrider branch. I don't know if you could read the info from these files. I'm sure it would be easier than comfy. Here is an example.
![2023-08-29_13-24-25_1047](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/142053317/9614f15b-e841-4b81-aef7-ac03c8731412)

**Comment by receyuki** [comment]
@Marscog Can you open a new issue of type "Format Support Request"? I took a quick look, and I believe I should be able to support this format quite easily.

**Comment by receyuki** [comment]
@GlebIgorevich @Marscog 
[SD-Prompt-Reader-1.3.3-beta.2-dev.1-Windows-x64.zip](https://github.com/receyuki/stable-diffusion-prompt-reader/files/12479221/SD-Prompt-Reader-1.3.3-beta.2-dev.1-Windows-x64.zip)
Try it out. (Hopefully the last dev version)

**Comment by Marscog** [comment]
The new version works for my files in comfy and fooocus MRE branch.
THANKS!

**Comment by receyuki** [comment]
@GlebIgorevich Both FaceDetailer and UltimateSDUpscale are custom nodes, and personally, I would prefer not to handle the parameters of custom nodes, as this would be another never-ending task. 

Also, both FaceDetailer and UltimateSDUpscale have very large number of parameters, even more than KSampler. If I include the custom node parameters in the settings, the settings will become really really long.

**Comment by receyuki** [comment]
I just released the SD Prompt Reader ComfyUI node version, try it out. If you encounter any issues or have any suggestions, please let me know.
https://github.com/receyuki/comfyui-prompt-reader-node

**Comment by WinstonWoof** [comment]
wonderful concept however point blank refuses to read anything saved with a standard ComfyUI Image Save node for me (### ComfyUI Revision: 1866 [1b103e0c] | Released on '2023-12-30')

Example Image attached

![Winston_413736592282329_20240103143309_00001_](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/128506111/2fa78d6d-b9f0-4a31-81cf-9a504a099a94)


NB using the Node version I get this

![image](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/128506111/fce30678-055f-448a-9547-5799df2fd9c7)

**Comment by receyuki** [comment]
@WinstonWoof The image above uses many custom nodes that are not supported by the SD Prompt Reader. It's best to use Prompt Saver node to ensure the metadata can be read by Prompt Reader or any other metadata reading tool.

The reason for this is quite simple: for each custom node, I have to support them individually. Although I have supported a large number of custom nodes, this is still an endless task. That's why I decided to make Prompt Saver node.

**Comment by llpppzzz** [comment]
Hi, I got some problems when using the prompt reader node, but the exe on windows works correctly
This image is generated by webui, it's a very simple text2img.
need help, thanks
![Image](https://github.com/user-attachments/assets/48869e05-2151-4010-8cc8-ac7f355a43a3)
nothing shows and no errors alert
![Image](https://github.com/user-attachments/assets/06274d46-8f46-421b-ae3e-25ae41da88c2)
