### ISSUE TITLE
Mac OSX 13.4.1  - Calling App during start - Force deletion

### ISSUE THREAD

**Issue by all4five** [receyuki/stable-diffusion-prompt-reader#28]
Hi I tried to download the universal DMG for

- 1.3.2
- 1.3.1
- 1.3.0 

But every time, OSX displays this message:
![Bildschirmfoto 2023-08-06 um 12 54 08](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/113880578/23b51778-33af-4cbd-a888-36832f63567b)
Reading: ""SD Prompt Reader.app" is corrupted and cannot be opened. It is recommended to move the object to the Trash."

What can I do to resolve this?

**Comment by receyuki** [comment]
Sorry for the inconvenience
https://github.com/receyuki/stable-diffusion-prompt-reader#sd-prompt-readerapp-is-damaged-and-cant-be-opened-you-should-move-it-to-the-trash

**Comment by receyuki** [comment]
No, it's my fault, I just don't want to spend the 99 bucks☹️
