### ISSUE TITLE
But ? this is not a stand alone ? so SDwebui needed to use it ?

### ISSUE THREAD

**Issue by AkoZ** [receyuki/stable-diffusion-prompt-reader#3]
1. if this is just out to .png prompt to know from an image.. i've to start web ui till ?
2. Or just webui is installed and i've to indicate the path ??
3. think about a standalone soft without charging any sampler or models .. ?
4. can it be a minimal without SD webui started ?

**Comment by AkoZ** [comment]
infact even i tried a venv from SDwebui nor a python setup.py .. nothing opens a good window to start ;)
plzzz don't forget noobies .. what's the start ? and HOW TO use this reader easy ? ;)

**Comment by receyuki** [comment]
> infact even i tried a venv from SDwebui nor a python setup.py .. nothing opens a good window to start ;) plzzz don't forget noobies .. what's the start ? and HOW TO use this reader easy ? ;)

First of all this app is just for reading prompts from a webui generated png. If the file is not generated by the webui (does not contain metadata), the app can't do anything about it. As for how to use it, the truth is that you really don't need anything to run it.
https://github.com/receyuki/stable-diffusion-prompt-reader/releases/latest
Just download the version that matches your os from the link above. For instance, if you're using windows, just download _sd-prompt-reader-x.x.x-windows-x64.zip_ and unzip it, then run the exe, and voila!
No python needed
No webui needed
So it's standalone
