### ISSUE TITLE
[FEATURE REQUEST] - Version number in the window title

### ISSUE THREAD

**Issue by Woisek** [receyuki/stable-diffusion-prompt-reader#30]
Just a small suggestion. Please display the version number in the window title, so that we know, which version we are running. 🙂

**Comment by receyuki** [comment]
If you are using Windows, right-click on the .exe file, select "Properties," and switch to the "Details" tab. If you are using macOS, select the app and press the space bar.

The next major release will add an "About" page, providing a more convenient way to view the version information.
