### ISSUE TITLE
[BUG] - does not always correctly read the seed from ComfyUI

### ISSUE THREAD

**Issue by lilixil** [receyuki/stable-diffusion-prompt-reader#33]
Example: ![ComfyUI_01807_](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/75931062/b468110a-1689-4634-b66f-9a0e3268ee38)  
You can drag the file into ComfyUI and see that it has a seed that allows you to recreate the same generated image.
You can find seed in this file (`"noise_seed": 1058386025918295`), and stable-diffusion-prompt-reader showing `Seed: None`.

![obraz](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/75931062/eeb72ce4-26d8-4247-9fa3-f40dadb8fd8f)

When i changed `control_after_generate` from `randomized` to `fixed` and use `1058386025918295` as a `noise_seed` (in KSampler Advanced - BASE) i can generate basically the same picture, so it has a seed. 

![ComfyUI_01850_](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/75931062/666c4b9f-434a-4e83-8d1d-23a08bc9b0c9)

I downloaded stable-diffusion-prompt-reader mainly for this, it would be nice if you would create an update.

**Comment by receyuki** [comment]
It seems like you are using SDXL, which is not currently supported. I will add support for SDXL in the next release.

**Comment by Tikishark777** [comment]
Do you have an estimate of when you think the next release will be available?  TY

**Comment by receyuki** [comment]
You seem to be in a hurry, so I've made a temporary version for you to fix this issue. But the next release may still take a few days (I've been drinking too much these days). If you don't experience any problems, you can use it as a normal version and update it as usual.
[SD-Prompt-Reader-1.3.2a2.dev1-Windows-x64.zip](https://github.com/receyuki/stable-diffusion-prompt-reader/files/12383984/SD-Prompt-Reader-1.3.2a2.dev1-Windows-x64.zip)

**Comment by Tikishark777** [comment]
Thank you.  I can totally wait for the full version.  Enjoy the summer and drink up : )

**Comment by lilixil** [comment]
> You seem to be in a hurry, so I've made a temporary version for you to fix this issue. But the next release may still take a few days (I've been drinking too much these days). If you don't experience any problems, you can use it as a normal version and update it as usual. [SD-Prompt-Reader-1.3.2a2.dev1-Windows-x64.zip](https://github.com/receyuki/stable-diffusion-prompt-reader/files/12383984/SD-Prompt-Reader-1.3.2a2.dev1-Windows-x64.zip)
#
Now the seed values ​​for the photo in question are shown correctly. Thanks!
___

I've identified another issue (which also occurs in the latest version, [1.3.3-beta.1](https://github.com/receyuki/stable-diffusion-prompt-reader/releases/tag/v1.3.3-beta.1)) - when you open the images below using the program, the positive prompt is not visible.
![ComfyUI_01938_](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/75931062/9533c05f-b33e-4b46-9ff3-ae8d75568d34)
↑ [ComfyUI_01938_.zip](https://github.com/receyuki/stable-diffusion-prompt-reader/files/12448185/ComfyUI_01938_.zip) ↑

![ComfyUI_01964_](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/75931062/47a3d5ba-9e0c-4af4-ab69-ee17388d883d)
↑ [ComfyUI_01964_.zip](https://github.com/receyuki/stable-diffusion-prompt-reader/files/12448188/ComfyUI_01964_.zip) ↑


___
Btw 1, it would be ok if the "Scheduler" were also displayed in the 3rd window in _Simple mode_ view, although it's not really crucial.

___
Btw 2, a somewhat facilitating feature for working with the program would be displaying the name of the open file, e.g. below/above the image or in the top bar.

**Comment by receyuki** [comment]
@lilixil This bug is the same as the bug with the norwegian forest cat, so it will also be fixed in beta2.
___

My idea is that the simple mode should display parameters that are common to all tools by default and are most commonly used by the majority of users. However, for most of the tools, the option to modify the scheduler is not displayed by default. Later on, I will add a user preferences interface. At that time, I can include an option to customize the content displayed in the simple mode.
___

In the upcoming gallery view mode mentioned in #31, the file name, modification time, and size of the images will be displayed. But honestly, in the current UI, I'm not sure where to place the file name. It feels like displaying it anywhere wouldn't be very aesthetically pleasing.

**Comment by receyuki** [comment]
@lilixil 
https://github.com/receyuki/stable-diffusion-prompt-reader/releases/tag/v1.3.3-beta.2
I just released beta 2. Try it out.

**Comment by lilixil** [comment]
@receyuki 
[v1.3.3-beta.2](https://github.com/receyuki/stable-diffusion-prompt-reader/releases/tag/v1.3.3-beta.2) solved the problem, thank you.
___
In terms of the aesthetics of the filename placement, I think that what it looks like [here](https://github.com/receyuki/stable-diffusion-prompt-reader/discussions/31#discussioncomment-6708036) is the most aesthetic way. It may look the same when displaying a single photo, not a gallery.

**Comment by receyuki** [comment]
@lilixil Alright, I'll take that into consideration.
