### ISSUE TITLE
[BUG] - On MacOS Monterey App cannot be started

### ISSUE THREAD

**Issue by technerd-official** [receyuki/stable-diffusion-prompt-reader#35]
### Description

When opening the App than MacOS says it's damaged and needs to be moved to the bin. Tried to remove the attributes to still start it somehow but it still won't. Now it redirects me to the debugging application: The py2app builder won’t always generate a working application out of the box for various reasons.

### Reproduction steps

Open App on MacOS

### Version

1.3.2

### OS

Mac

### Tool

A1111's webUI

**Comment by hugepower** [comment]
Hello, I'm sorry to hear that you encountered this problem. It seems that your app is blocked by the MacOS security system, which prevents it from opening. To fix this, please try the following steps:

1. Re-download the app from the GitHub page.
2. Install the app in the "Applications" folder.
3. Open the Terminal app and run this command:

```
xattr -r -d com.apple.quarantine /Applications/SD\ Prompt\ Reader.app
```

This command will remove the quarantine attribute from the app, which should allow it to run normally. You can find more details about this issue and the solution here.

[https://github.com/receyuki/stable-diffusion-prompt-reader#sd-prompt-readerapp-is-damaged-and-cant-be-opened-you-should-move-it-to-the-trash](https://github.com/receyuki/stable-diffusion-prompt-reader#sd-prompt-readerapp-is-damaged-and-cant-be-opened-you-should-move-it-to-the-trash)



Please let me know if this works for you or if you have any other questions. Thank you for using SD Prompt Reader!

**Comment by technerd-official** [comment]
Thank you very much, I did that but it still doesn't work. I get the "Launch error" with redirecting me to the py2app website. See the Screenshot.

![Screenshot 2023-08-25 at 18 57 53](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/143012532/9f8dbb3e-26d1-4b3b-9a17-c1d45d131362)

**Comment by hugepower** [comment]
> Thank you very much, I did that but it still doesn't work. I get the "Launch error" with redirecting me to the py2app website. See the Screenshot.
> 
> ![Screenshot 2023-08-25 at 18 57 53](https://user-images.githubusercontent.com/143012532/263342920-9f8dbb3e-26d1-4b3b-9a17-c1d45d131362.png)

Sorry, I misunderstood your question before. 

You can try to run your `SD\ Prompt\ Reader.app/Contents/MacOS/SD\ Prompt\ Reader` executable file and see what information it displays when it starts.

For example:

```
➜  ~ /Users/hugepower/stable-diffusion-prompt-reader/dist/SD\ Prompt\ Reader.app/Contents/MacOS/SD\ Prompt\ Reader ; exit;
/Users/hugepower/stable-diffusion-prompt-reader/dist/SD Prompt Reader.app/Contents/Resources/__boot__.py:216: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "/Users/hugepower/stable-diffusion-prompt-reader/dist/SD Prompt Reader.app/Contents/Resources/__boot__.py", line 261, in <module>
    _run()
  File "/Users/hugepower/stable-diffusion-prompt-reader/dist/SD Prompt Reader.app/Contents/Resources/__boot__.py", line 133, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Users/hugepower/stable-diffusion-prompt-reader/dist/SD Prompt Reader.app/Contents/Resources/main.py", line 1, in <module>
    from sd_prompt_reader.app import main
  File "sd_prompt_reader/app.pyc", line 19, in <module>
  File "sd_prompt_reader/image_data_reader.pyc", line 18, in <module>
  File "logging/__init__.pyc", line 2050, in basicConfig
  File "logging/__init__.pyc", line 1181, in __init__
  File "logging/__init__.pyc", line 1213, in _open
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hugepower/stable-diffusion-prompt-reader/dist/SD Prompt Reader.app/Contents/Resources/Logs/image_data_reader.log'
2023-08-26 02:11:37.990 SD Prompt Reader[15276:373276] Launch error
2023-08-26 02:11:37.990 SD Prompt Reader[15276:373276] Launch error
See the py2app website for debugging launch issues

Saving session...completed.
```

I had the same problem as you before. 

In my case, my error message was:

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hugepower/stable-diffusion-prompt-reader/dist/SD Prompt Reader.app/Contents/Resources/Logs/image_data_reader.log'
```

I encountered an error when I ran the program after packaging, because I used a relative path to specify the location of the log that I added to the project by myself. 

<img width="558" alt="image" src="https://github.com/receyuki/stable-diffusion-prompt-reader/assets/46076022/ad3bb889-413b-45f6-ba0d-7358a0a76c4f">

After solving this problem and recompiling, the program ran normally. 

This is just for your reference.

**Comment by receyuki** [comment]
Based on my experience, this issue might be caused by the antivirus you are using. If you are using any antivirus , please try adding the app to the whitelist and see if that helps. If you are not using any antivirus, please follow these steps to provide me with more information.

1. Right-click on the SD Prompt Reader.app.
2. Select "Show Package Contents".
3. In the /Contents/MacOS/ directory, you will find a file named "SD Prompt Reader" like this <img width="141" alt="截屏2023-08-27 上午12 01 15" src="https://github.com/receyuki/stable-diffusion-prompt-reader/assets/28808141/32aacc4f-48dc-4643-87c0-ca65642cf7c3">
5. Open Terminal and drag this file into the Terminal window, then press Enter.
6. Capture screenshots of all the information displayed in the Terminal.

Thank you so much.

**Comment by technerd-official** [comment]
Dragged it into Terminal and I get the same error when first time trying to run the app.
![Screenshot 2023-08-26 at 18 09 49](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/143012532/eee683e7-8973-4567-b703-b7d89021def7)

**Comment by receyuki** [comment]
Is there any information displayed on the Terminal? And you're not using any antivirus, right?

**Comment by technerd-official** [comment]
no antivirus. Thats all that is displayed in terminal: zsh: killed /Applications/SD\ Prompt\ Reader.app/Contents/MacOS/SD\ Prompt\ Reader

**Comment by hugepower** [comment]
> Dragged it into Terminal and I get the same error when first time trying to run the app. Terminal: zsh: killed /Applications/SD\ Prompt\ Reader.app/Contents/MacOS/SD\ Prompt\ Reader ![Screenshot 2023-08-26 at 18 09 49](https://user-images.githubusercontent.com/143012532/263475170-eee683e7-8973-4567-b703-b7d89021def7.png)

It seems that this error was caused by you forgetting to do this operation.

```
xattr -r -d com.apple.quarantine /Applications/SD\ Prompt\ Reader.app
```

Since the program does not have a developer signature, you need to manually execute it in the terminal every time you install it.

**Comment by hugepower** [comment]
> Thank you very much, I did that but it still doesn't work. I get the "Launch error" with redirecting me to the py2app website. See the Screenshot.
> 
> ![Screenshot 2023-08-25 at 18 57 53](https://user-images.githubusercontent.com/143012532/263342920-9f8dbb3e-26d1-4b3b-9a17-c1d45d131362.png)

When you encounter this problem again, you can try to run your `/Applications/SD\ Prompt\ Reader.app/Contents/MacOS/SD\ Prompt\ Reader` executable file and see what information it displays when it starts.

For example:

```
➜  ~ /Users/hugepower/stable-diffusion-prompt-reader/dist/SD\ Prompt\ Reader.app/Contents/MacOS/SD\ Prompt\ Reader ; exit;
/Users/hugepower/stable-diffusion-prompt-reader/dist/SD Prompt Reader.app/Contents/Resources/__boot__.py:216: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "/Users/hugepower/stable-diffusion-prompt-reader/dist/SD Prompt Reader.app/Contents/Resources/__boot__.py", line 261, in <module>
    _run()
  File "/Users/hugepower/stable-diffusion-prompt-reader/dist/SD Prompt Reader.app/Contents/Resources/__boot__.py", line 133, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Users/hugepower/stable-diffusion-prompt-reader/dist/SD Prompt Reader.app/Contents/Resources/main.py", line 1, in <module>
    from sd_prompt_reader.app import main
  File "sd_prompt_reader/app.pyc", line 19, in <module>
  File "sd_prompt_reader/image_data_reader.pyc", line 18, in <module>
  File "logging/__init__.pyc", line 2050, in basicConfig
  File "logging/__init__.pyc", line 1181, in __init__
  File "logging/__init__.pyc", line 1213, in _open
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hugepower/stable-diffusion-prompt-reader/dist/SD Prompt Reader.app/Contents/Resources/Logs/image_data_reader.log'
2023-08-26 02:11:37.990 SD Prompt Reader[15276:373276] Launch error
2023-08-26 02:11:37.990 SD Prompt Reader[15276:373276] Launch error
See the py2app website for debugging launch issues

Saving session...completed.
```

We need this information to determine what kind of problem you encountered.

**Comment by receyuki** [comment]
https://github.com/receyuki/stable-diffusion-prompt-reader/releases/tag/v1.3.3-beta.2
@technerd-official Please try this verison. I recompiled some modules, and it should work fine on Apple Silicon now. I apologise for not testing 1.3.2 thoroughly enough.

**Comment by skein12** [comment]
> 

still says it's damaged, ended up installing from brew

**Comment by moon47usaco** [comment]
I have the same issue with all versions.

**Comment by receyuki** [comment]
@moon47usaco 
https://github.com/receyuki/stable-diffusion-prompt-reader#sd-prompt-readerapp-is-damaged-and-cant-be-opened-you-should-move-it-to-the-trash
Have you tried this or tried installing it via brew?

**Comment by moon47usaco** [comment]
Thank you, command line fix works.
