### ISSUE TITLE
[BUG] - Images created before 3-14-2023 in invoke will not open

### ISSUE THREAD

**Issue by Void2258** [receyuki/stable-diffusion-prompt-reader#36]
### Description

As described, images created on 3-13-2023 or earlier in invoke AI will not open. No error message or anything, simply nothing happens when dragged in. This roughly corresponds to release 2.3.2, so it's possible this is something to do with versions prior to that one.

### Reproduction steps

Drag image with date older than 3-13-2023 into the window. 
Absolutely nothing happens.

### Image file

From 3-13-2023: 
![000226 b88cee60 3343013051](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/6126362/dd6a1ac1-e7cd-4fd1-b032-3ad496133855)

From 3-15-2023: 
![000269 d4720354 3336898598 postprocessed](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/6126362/94b4f547-5372-40e6-aaf9-ca097f3295bd)

### Version

1.3.2

### OS

Windows

### Tool

InvokeAI

**Comment by receyuki** [comment]
I have confirmed that the prompt sections of these two images are slightly different. Thank you for providing the image from the early versions of Invoke AI. This will allow me to make SD Prompt Reader support a wider range of formats. I will be releasing beta2 within the next few days to solve this issue.

**Comment by Void2258** [comment]
You might want to check on the Invoke discord regarding even earlier versions.

**Comment by receyuki** [comment]
https://github.com/receyuki/stable-diffusion-prompt-reader/releases/tag/v1.3.3-beta.2
I just released beta 2. Try it out.
