### ISSUE TITLE
1.3.3-beta.2 无法启动

### ISSUE THREAD

**Issue by amiglistimo** [receyuki/stable-diffusion-prompt-reader#38]
### Description

打开提示：Launch error，See the py2app website for debugging launch issues

### Reproduction steps

MacBook Pro M1
macOS 13.5.1

### Version

1.3.2

### OS

Mac

### Tool

A1111's webUI

**Comment by receyuki** [comment]
https://github.com/receyuki/stable-diffusion-prompt-reader/releases/tag/v1.3.3-beta.2
试一下这个版本，上个版本我测试做的不够全，实在抱歉

**Comment by amiglistimo** [comment]
> https://github.com/receyuki/stable-diffusion-prompt-reader/releases/tag/v1.3.3-beta.2
> 重新试一下这个版本，之前我测试做的不够全，实在抱歉。版本号没改只是换了出问题的模组重新打了包

可以用了，谢谢！
