### ISSUE TITLE
Open with... not work

### ISSUE THREAD

**Issue by BoyNG** [receyuki/stable-diffusion-prompt-reader#4]
I try open via Windows context menu (Open with... and choose "SD Prompt Reader.exe") or direct Drag'N'Drop to exe and it's not work!
Why?!

**Comment by receyuki** [comment]
> I try open via Windows context menu (Open with... and choose "SD Prompt Reader.exe") or direct Drag'N'Drop to exe and it's not work! Why?!

Please open the exe first, then drag n drop the image into the window. 
The two types of interaction you mentioned are not currently implemented. (Due to some limitations of python)
