### ISSUE TITLE
[BUG] - Prompt can not be read from WEBP & JPEG Images generated by A1111

### ISSUE THREAD

**Issue by AdamXJ** [receyuki/stable-diffusion-prompt-reader#41]
### Description

Version **1.3.3** Is unable to read the prompt from **WEBP & JPEG** Images generated by **A1111's webUI**. I'm not sure if files created by other generators are affected... since this is the only one I use.

**PNG, WEBP & JPEG** files can be read without issues using the previous Prompt Reader version (**1.3.2**). **PNGs** are still readable in the new version but not the other two format.

### Reproduction steps

**1.** Open these image files (webp or jpeg) in Prompt Reader 1.3.3 in any way (file picker, drag&drop, file association, "send to..." menu) on Windows (I used Windows 11).

**2.** See error message:
![cube-error](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/17956609/853e6708-6c0b-48b7-be68-be2e764fb2bb)

### Image file

These are the images I used for testing: [test-images.zip](https://github.com/receyuki/stable-diffusion-prompt-reader/files/12513598/test-images.zip)

### Version

1.3.3

### OS

Windows

### Tool

A1111's webUI

**Comment by receyuki** [comment]
OMG! You're right! It seems like this bug was caused by adding support for StableSwarmUI. I will fix it ASAP. 
~~I can't believe I didn't catch this bug during testing.~~
