### ISSUE TITLE
[BUG] - Cannot Download

### ISSUE THREAD

**Issue by Piscabo** [receyuki/stable-diffusion-prompt-reader#42]
### Description

Newest Update cannot be downloaded on Windows?

### Reproduction steps

Virus detected, cannot download? Windows 11

### Image file

![image](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/123719842/e9049be9-a635-4c06-a239-3213dad96c79)

### Version

1.3.3

### OS

Windows

### Tool

A1111's webUI

**Comment by receyuki** [comment]
This is weird, downloading this zip on my Chrome 116 only shows a warning of uncommon download.

**Comment by Piscabo** [comment]
> Try this out and let me know what message the browser displays. [SD-Prompt-Reader-1.3.3-post.1-dev.1-Windows-x64.zip](https://github.com/receyuki/stable-diffusion-prompt-reader/files/12540129/SD-Prompt-Reader-1.3.3-post.1-dev.1-Windows-x64.zip)

Download now, but shows this: 
![image](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/123719842/ed28f1f3-9fc3-4362-9535-0cddd52fd90d)
Thanks for the fix!

**Comment by receyuki** [comment]
Since I haven't spent hundred bucks on code signing, this warning is expected. I will change released exe to this version later to prevent more people from encountering the same situation as you did.
