### ISSUE TITLE
[FEATURE REQUEST] - version number

### ISSUE THREAD

**Issue by iTeddyBe** [receyuki/stable-diffusion-prompt-reader#48]
### Summary

Add version number to program window title

### Basic Example

SD Prompt Reader v.1.3.4

**Comment by Woisek** [comment]
https://github.com/receyuki/stable-diffusion-prompt-reader/issues/30

**Comment by receyuki** [comment]
It seems like everyone really wants an intuitive way to check the version number, so I think it's better to add one.

**Comment by iTeddyBe** [comment]
> It seems like everyone really wants an intuitive way to check the version number, so I think it's better to add one.

tnx ;)
