### ISSUE TITLE
[BUG]: Unhandled exception

### ISSUE THREAD

**Issue by Woisek** [receyuki/stable-diffusion-prompt-reader#50]
### Description

I'm playing with ComfyUI lately and now, when I want to open a PNG with PR, I get an error.
Can't tell what happened. 🤔

### Reproduction steps

Open image with PR

### Image file

![Zwischenablagebild](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/122026301/4c637e07-0e12-403f-90ca-acfb48db84c0)

### Version

1.3.3

### OS

Windows

### Tool

ComfyUI

**Comment by receyuki** [comment]
Have you tried 1.3.4beta1? If the same bug still appears, please post the image here or send to my email.
2023年10月10日 +0800 AM6:27 Woisek ***@***.***>，写道：
