### ISSUE TITLE
[BUG] - Malware alert

### ISSUE THREAD

**Issue by justanotherbug** [receyuki/stable-diffusion-prompt-reader#56]
### Description

Window 11 flags the app as a virus. Chrome does not allow the download to finish. Firefox allows the download but after i unzip the file, i double click the exe and windows gives this error.

### Image file

![Screenshot 2023-10-30 141342](https://github.com/receyuki/stable-diffusion-prompt-reader/assets/9277000/a8c246a6-b7c8-4f13-931b-f90e59caa59e)

### Version

1.3.4

### OS

Windows

### Tool

A1111's webUI

**Comment by receyuki** [comment]
Thank you for your feedback. The malware alert on Windows has been fixed in `SD-Prompt-Reader-1.3.4-Windows-x64-v2.zip`. Please re-download it.
https://github.com/receyuki/stable-diffusion-prompt-reader/releases/tag/v1.3.4
