### ISSUE TITLE
App wont open for me - “SD Prompt Reader is damaged and can’t be opened. You should move it to the Bin."

### ISSUE THREAD

**Issue by mikestreed** [receyuki/stable-diffusion-prompt-reader#62]
### Description

v1.3.4
MacBook Air M1 8GB with MacOS 12.6

### Version

1.3.4

### OS

Mac (Apple silicon)

### Tool

ComfyUI

**Comment by receyuki** [comment]
Please reinstall via homebrew
https://github.com/receyuki/stable-diffusion-prompt-reader#install-via-homebrew-cask

or follow this instruction to remove the quarantine attributes
https://github.com/receyuki/stable-diffusion-prompt-reader#sd-prompt-readerapp-is-damaged-and-cant-be-opened-you-should-move-it-to-the-trash

**Comment by mikestreed** [comment]
Ah yes, thanks
