### ISSUE TITLE
Beta 1 flagged by Antivirus.

### ISSUE THREAD

**Issue by danrazor** [receyuki/stable-diffusion-prompt-reader#74]
### Description

Beta 1 was flagged by antivirus AVIRA and put on quarantine.
says it is infected with ...
"Drop.Win64.LocalAppSelfRun.21014"

kindly submit the build to them so they stop flagging it.

thanks

### Version

1.3.4

### OS

Windows

### Tool

A1111's webUI

**Comment by danrazor** [comment]
just recalling Github system wide infections in recent months, could this be related to github injecting something in builds rather than devs doing something wrong?

**Comment by receyuki** [comment]
I will update the library that causes false positives to the latest version in beta2, hoping this can solve the problem.

**Comment by receyuki** [comment]
beta2 is here! Hope AVIRA likes it.
https://github.com/receyuki/stable-diffusion-prompt-reader/releases/tag/v1.3.5-beta.2
