### ISSUE TITLE
[FEATURE REQUEST] - Regarding the behavior of the Save button

### ISSUE THREAD

**Issue by vivalavida1977** [receyuki/stable-diffusion-prompt-reader#75]
### Summary

I want it to be selectable. In my usage, I only do overwrite saves, so I want to skip the step of opening the pull-down menu

### Basic Example

I want it to be selectable. In my usage, I only do overwrite saves, so I want to skip the step of opening the pull-down menu

**Comment by receyuki** [comment]
This will be part of the user preference panel, which is already planned, but I have been busy with other things and haven't had time to complete the user preference panel.

**Comment by vivalavida1977** [comment]
Thank you for your response. Your app is becoming more and more invaluable for me as I use it every day. I am grateful that you made it public. I will patiently await any updates☺️
